name: Nightly tests against Prefect's main branch
on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  submit-update-pr:
    name: Run tests against Prefect's main branch
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Set up uv and Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}
          cache-dependency-glob: "pyproject.toml"

      - name: Run tests
        env:
          PREFECT_SERVER_DATABASE_CONNECTION_URL: "sqlite+aiosqlite:///./collection-tests.db"
        run: |
          uv add "prefect @ git+https://github.com/PrefectHQ/prefect.git@main"
          uv run pytest tests -vv
