name: Build & Release

on:
  push:
    tags:
      - "v*"

permissions:
  id-token: write
  contents: write
  checks: write
  packages: write

jobs:
  build-release:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up uv and Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}
          cache-dependency-glob: "pyproject.toml"

      - run: uv build

      - name: Publish build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: built-package
          path: "./dist"

  publish-release:
    name: Publish release to PyPI
    needs: [build-release]
    environment: "prod"
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v5
        with:
          name: built-package
          path: "./dist"

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true

  build-and-publish-docs:
    name: Build and publish docs
    needs: [build-release, publish-release]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          python-version: 3.12
          cache-dependency-glob: "pyproject.toml"

      - run: >
               uv run mkdocs build

      - name: Publish docs
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          branch: docs
          folder: site
