name: Tests

on: 
  pull_request:
  workflow_dispatch:

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
      fail-fast: false
    steps:
      - uses: actions/checkout@v5

      - name: Set up uv and Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}
          cache-dependency-glob: "pyproject.toml"

      - name: Run tests with coverage
        run: |
          uv run coverage run -m pytest tests -vv
          uv run coverage report
        env:
          PREFECT_SERVER_DATABASE_CONNECTION_URL: "sqlite+aiosqlite:///./collection-tests.db"

      - run: uv run mkdocs build --verbose --clean
